version: '3'
services:
  auth_db:
    image: 'mongo:latest'
    ports: 
      - '27017:27017'
  auth:
    build: './services/auth'
    depends_on: 
      - 'auth_db'
    ports: 
      - '8001:8001'
  messages:
    build: './services/messages'
    ports: 
      - '8002:8002'
  web:
    build: './services/web'
    ports: 
      - '8003:8003'