version: '3'
services:
  auth_db:
    image: 'mongo:latest'
    ports: 
      - '9101:27017'
  msg_db:
    image: 'mongo:latest'
    ports: 
      - '9102:27017'
  auth:
    build: './services/auth'
    environment: 
      - DB_PORT=9101
    depends_on: 
      - 'auth_db'
    ports: 
      - '9001:9001'
  messages:
    build: './services/messages'
    environment: 
      - DB_PORT=9102
    depends_on: 
      - 'msg_db'
    ports: 
      - '9002:9002'
  web:
    build: './services/web'
    ports: 
      - '9003:9003'